CREATE DATABASE 4thewords_prueba_rubert_gonzalez;
USE 4thewords_prueba_rubert_gonzalez;

CREATE TABLE IF NOT EXISTS legend (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    legend_date DATE NOT NULL,
    province VARCHAR(100) NOT NULL,
    canton VARCHAR(100) NOT NULL,
    district VARCHAR(100) NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO legend (name, category, description, legend_date, province, canton, district, image_url) VALUES
('La Tulevieja', 'Fantasia', 'Espiritu de una mujer que, por abandonar a su hijo recien nacido, fue condenada a vagar eternamente por los rios de Costa Rica. Su apariencia es aterradora, con un rostro deformado y sucio, y suele aparecerse en noches de lluvia, lamentandose por su perdida.', '1920-04-03', 'Cartago', 'Turrialba', 'Santa Cruz', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/tulevieja.jpg?alt=media&token=6480772e-1a24-4113-85a1-7732eda442e8'),
('El Cadejos', 'Misterio', 'Se dice que un enorme perro negro con ojos brillantes y cadenas arrastrandose sigue a los borrachos y a los caminantes nocturnos. Aunque muchos lo ven como una criatura demoniaca, otros aseguran que protege a los inocentes y castiga a los malvados, desapareciendo al amanecer.', '1905-10-23', 'San Jose', 'San Jose', 'Hospital', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/cadejos.jpeg?alt=media&token=878e9211-1f5f-4abd-86a2-ebbba97086f0'),
('La Llorona', 'Terror', 'Espiritu de una mujer que fue condenada a llorar por la eternidad tras haber ahogado a sus hijos en un rio. En las noches oscuras, su lamento desgarrador resuena en las orillas, asustando a quienes la escuchan y llenandolos de un profundo escalofrio.', '1890-05-15', 'Alajuela', 'Grecia', 'San Isidro', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/la-llorona.jpeg?alt=media&token=f9dc9956-aae7-4bc2-8ce9-a5e30c67e3e7'),
('La Carreta sin Bueyes', 'Misterio', 'Una carreta espectral que recorre las calles de los pueblos en las noches sin luna. Su rechinar espeluznante y su avance sin conductor ni animales es una señal de que alguien cercano morira pronto. Se dice que aquellos que la ven sufren de pesadillas y una sensacion de muerte inminente.', '1885-11-07', 'Heredia', 'Heredia', 'Mercedes', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/la-carreta-sin-bueyes.jpeg?alt=media&token=9ea044f4-d6a5-4056-9330-3a293e77fc09'),
('El Padre sin Cabeza', 'Terror', 'Un sacerdote que, tras cometer actos impuros, fue condenado a vagar sin cabeza por los pasillos de iglesias y conventos. Se dice que su presencia se siente a traves de una brisa helada y murmullos escalofriantes que llenan de panico a quienes los escuchan.', '1870-09-12', 'Puntarenas', 'Esparza', 'Espiritu Santo', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/el-padre-sin-cabeza.jpeg?alt=media&token=e1360275-6c9a-4aa9-bf23-e060746d14f0'),
('La Segua', 'Terror', 'Una mujer de belleza incomparable se aparece en los caminos solitarios a los hombres infieles. Al acercarse, su rostro se transforma en el de un ser monstruoso con cabeza de caballo y ojos ardientes, provocando panico y locura en quienes la ven.', '1800-07-22', 'Cartago', 'Cartago', 'Oriental', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/la-segua.jpeg?alt=media&token=30e4f3e7-4dc1-4ef5-89fd-c94ad616a671'),
('El Micomalo', 'Fantasia', 'Un ser con apariencia de mono gigante que habita en las profundidades de la selva de Costa Rica. Se dice que emite gritos aterradores y que ataca a los viajeros desprevenidos, llevandolos a su guarida para nunca ser vistos de nuevo.', '1930-06-18', 'Limon', 'Talamanca', 'Bribri', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/El-Mico-Malo.jpg?alt=media&token=179eadd6-a031-446c-9aa9-89bcfc20933c'),
('El Sisimiqui', 'Misterio', 'Un duende jugueton que habita en los bosques y disfruta gastando bromas a los caminantes. Se dice que puede imitar voces humanas y que usa su risa para desorientar a las personas, haciendolas perder el camino.', '1882-03-15', 'San Jose', 'Desamparados', 'San Rafael Abajo', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/sisimiqui.jpeg?alt=media&token=b59e3e0b-df65-420c-a069-6e4b36f06292'),
('Los Duendes de Costa Rica', 'Fantasia', 'Pequenos seres magicos que habitan en las montanas y bosques del pais. Son traviesos y les encanta jugar bromas a los humanos, escondiendo sus objetos o desordenando sus casas. A veces, pueden ser bondadosos y ayudar a los viajeros extraviados.', '1900-05-22', 'Guanacaste', 'Liberia', 'Canas Dulces', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/los-duendes.jpg?alt=media&token=13bad50b-7953-4d6f-b979-70bb4d7d0400'),
('El Dueno del Monte', 'Misterio', 'Un espiritu ancestral que protege los bosques y castiga a quienes los dañan. Se aparece a los cazadores furtivos y a quienes talan arboles sin permiso, asustandolos hasta que huyen aterrorizados. Algunos dicen que tiene forma de hombre con ojos brillantes y una larga capa de hojas.', '1956-06-14', 'Cartago', 'Turrialba', 'Central', 'https://firebasestorage.googleapis.com/v0/b/portafolio-web-c279e.appspot.com/o/due%C3%B1o-del-monte.jpg?alt=media&token=6a8c5d00-2baf-43ac-a6fb-972df77a664e');